### ISSUE TITLE
Support for Predicate with Date Datatype

### ISSUE THREAD

**Issue by luisenriqueramos1977** [fluree/ledger#184]
In the list of types supported by fluree predicates:

https://developers.flur.ee/docs/concepts/infrastructure/system_collections/#_predicate-types

I do not find the date datatype, how should I do to represent dates?

Luis Ramos

**Comment by fdmmarshall** [comment]
Hi @luisenriqueramos1977 thanks for you inquiry. You could use the `instant` datatype in fluree, it saves the date as a unix epoch timestamp that can be converted to a readable date.
