### ISSUE TITLE
restrictCollection from one to many

### ISSUE THREAD

**Issue by luisenriqueramos1977** [fluree/ledger#186]
I saw that restrictCollection can be applied to one collection, but what should I do if I have one to many?, 
how to deal when I have many collection as target?.

Luis

**Comment by fdmmarshall** [comment]
Hello @luisenriqueramos1977, at this time we don't have the functionality implemented to set restrictCollection as multi-cardinality, but we do have it in our backlog and hope to implement it in the future.
