### ISSUE TITLE
Why clojure why not rust?

### ISSUE THREAD

**Issue by ansarizafar** [fluree/ledger#19]
Flureedb is an amazing tech with some very interesting ideas but why it's written in clojure, why not in a fast, efficient and memory safe system programming language like Rust? 

Writing smart functions in clojure is very difficult for developers who don't understand/like clojure. Is there a plan to support JavaScript?

A visual data modeling and data editing GUI like terminusdb will help in flureedb adaption.

I would also recommend creating a discord server for community support. Discord is better for developers then slack and lots of other projects are using it.

Flureedb written in rust with an embedded  V8 engine for writing smart functions and business logic in JavaScript/WASM will make flureedb next generation server less platform.

**Comment by bplatz** [comment]
@ansarizafar There isn't just one reason for Clojure, but Fluree itself is a data-first platform built on immutable data structures (including immutable persistent data structures). That, in a nutshell, basically describes Clojure the language as well - it is well suited to the task.
