### ISSUE TITLE
And operator is not working as expected in RestApi

### ISSUE THREAD

**Issue by abhishekmishra17** [fluree/ledger#38]
I have created predicate as
[
    {
        "_id": "_predicate",
        "name": "testCollection/key",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/documentId",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/eventTime",
        "unique": false,
        "type": "instant",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/createdAt",
        "unique": false,
        "type": "instant",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/userId",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/actionType",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/data",
        "doc": "searchabel key",
        "unique": false,
        "type": "json",
        "fullText": true
    }
]

After that I have inserted record as
[
    {
        "key": "key1",
        "_id": 351843720888322,
        "eventTime": 1416615754,
        "userId": "user1",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    },
    {
        "key": "key2",
        "_id": 351843720888321,
        "eventTime": 1416788554,
        "userId": "user2",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    },
    {
        "key": "key1",
        "_id": 351843720888320,
        "eventTime": 1416615754,
        "userId": "user1",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    }
]

Now I am doing below search query for which I am not getting output
curl --location --request POST 'http://localhost:8080/fdb/xxx/yyyy/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "select": [
        "key",
        "eventTime",
        "userId",
        "actionType",
        "data"
    ],
   "where":" testCollection/eventTime >= 1416788554 AND testCollection/key = \"key2\""
    
    
}'

**Comment by ldw1007** [comment]
Hi @abhishekmishra17,
The query above looks like a combination of flureeql/sql - there does appear to be an issue with the SQL version excluding instants that are equal to 1416788554. We are tracking that issue as FC-1075.

For the SQL, I modified the query per our [docs](https://docs.flur.ee/docs/1.0.0/query/sql) and submitted the query to the "sql" API endpoint.

```
curl 'http://localhost:8090/fdb/***/***/sql' \
  -H 'Connection: keep-alive' \
  -H 'Authorization: Bearer undefined' \
  -H 'Request-Timeout: 20000' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  --data-raw $'"SELECT *\\n  FROM testCollection\\nWHERE eventTime >= 1416788554 \\n  AND key = \'key2\'\\n\\n"' \
  --compressed
```

---
The FlureeQL version appears to work correctly. 
```
{
"select": {"?testCollection": ["*"]},
"where":[["?testCollection", "rdf:type", "testCollection"],
         ["?testCollection", "testCollection/key", "#(= \"key2\" ?key)"],
         ["?testCollection", "testCollection/eventTime", "#(>= ?etime 1416788554)"]]
}
```

```
curl 'http://localhost:8090/fdb/***/***/query' \
  -H 'Connection: keep-alive' \
  -H 'Authorization: Bearer undefined' \
  -H 'Request-Timeout: 20000' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  --data-raw '{"select":{"?testCollection":["*"]},"where":[["?testCollection","rdf:type","testCollection"],["?testCollection","testCollection/key","#(= \"key2\" ?key)"],["?testCollection","testCollection/eventTime","#(>= ?etime 1416788554)"]]}' \
  --compressed
```

**Comment by abhishekmishra17** [comment]
Hi @ldw1007 ,

Thanks for the fast response. I tried the same and it working now. You can close this issue. It will be great if we came to know about a tentative time of SQL issue(FC-1075) fix.

**Comment by abhishekmishra17** [comment]
Hi @ldw1007 ,

Thanks for the fast response. I tried the same and it working now. . It will be great if we came to know about a tentative time of SQL issue(FC-1075) fix.

**Comment by ldw1007** [comment]
Hi @abhishekmishra17,

Reopening this ticket so we can track the resolution of the SQL issue here.  Since SQL and v1.0 are still in "beta", this issue is not prioritized as a blocker.  We will discuss it in our next planning meeting (Monday) - most likely it will be picked up then.

Have you joined our [Slack](https://launchpass.com/flureedb) community?  We have a collaborative environment with our users, we discuss how-tos, new features, bugs, workarounds, etc.

-Lois

**Comment by ldw1007** [comment]
The fix for this issue has been merged into the main branch.  
The next build for Fluree, v1.0.0rc-16, will contain the fix.
