### ISSUE TITLE
Unable to reterive record through _id which is generate by Fluree

### ISSUE THREAD

**Issue by abhishekmishra17** [fluree/ledger#41]
I have  created predicated as
[
    {
        "_id": "_predicate",
        "name": "testCollection/key",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/documentId",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/eventTime",
        "unique": false,
        "type": "instant",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/createdAt",
        "unique": false,
        "type": "instant",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/userId",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/actionType",
        "unique": false,
        "type": "string",
        "index": true
    },
    {
        "_id": "_predicate",
        "name": "testCollection/data",
        "doc": "searchabel key",
        "unique": false,
        "type": "json",
        "fullText": true
    }
]
and inserted some record. While fetching record I am getting addition node as _id which is unique per record
[
    {
        "key": "key1",
        "_id": 351843720888322,
        "documentId": "doc1",
        "eventTime": 1416615754,
        "createdAt": 1616680126,
        "userId": "user1",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    },
    {
        "key": "key2",
        "_id": 351843720888321,
        "documentId": "doc2",
        "eventTime": 1416788554,
        "createdAt": 1616680126,
        "userId": "user2",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    },
    {
        "key": "key1",
        "_id": 351843720888320,
        "documentId": "doc1",
        "eventTime": 1416615754,
        "createdAt": 1616680125,
        "userId": "user1",
        "actionType": "AUDIT.UPDATED",
        "data": "{\"name\":\"abhishek\",\"deatil\":\"NA\"}"
    }
]

Now I need to retrieve the record using _id. from which I tried the below curl request

curl --location --request POST 'http://localhost:8080/fdb/coverself/audit/query' \
--header 'Connection: keep-alive' \
--header 'Authorization: Bearer undefined' \
--header 'Request-Timeout: 20000' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--data-raw '{
    "select": {
        "?test": [
            "*"
        ]
    },
    "where": [
        [
            "?test",
            "rdf:type",
            "testCollection"
        ],
        [
            "?test",
            "testCollection/_id",
            "#(= 351843720888322 ?id)"
        ]
    ]
}'

But it responded as 
{
    "status": 400,
    "message": "Invalid predicate provided: testCollection/_id",
    "error": "db/invalid-query"
}

**Comment by ldw1007** [comment]
Hi @abhishekmishra17,

The query provided is incorrect because the fluree-generated _id is not part of testCollection.  You can execute a query directory using the _id using` "from": 351843720888322`

Have you joined our Slack community? We have Flurreans watching the different channels to answer questions like this.

-Lois
